[2016-03-22 15:05:21.833] [DEBUG] cheese - []
[2016-03-22 15:10:13.876] [DEBUG] cheese - [ DependenciesBlock {
    dependencies: [ [Object], [Object] ],
    blocks: [],
    variables: [],
    context: 'e:\\git\\yspm',
    reasons: [],
    debugId: 1000,
    lastId: -1,
    id: 0,
    index: 0,
    index2: 6,
    chunks: [ [Object] ],
    warnings: [],
    dependenciesWarnings: [],
    errors: [],
    dependenciesErrors: [],
    name: 'common',
    built: true,
    cacheable: true,
    issuer: null,
    useSourceMap: true,
    building: undefined },
  DependenciesBlock {
    dependencies: [ [Object], [Object] ],
    blocks: [],
    variables: [],
    context: 'e:\\git\\yspm\\src\\g\\js',
    reasons: [ [Object] ],
    debugId: 1002,
    lastId: -1,
    id: 1,
    index: 1,
    index2: 2,
    chunks: [ [Object] ],
    warnings: [],
    dependenciesWarnings: [],
    errors: [],
    dependenciesErrors: [],
    request: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\g\\js\\g.js',
    userRequest: 'e:\\git\\yspm\\src\\g\\js\\g.js',
    rawRequest: 'e:\\git\\yspm\\src\\g\\js\\g.js',
    parser: 
     Parser {
       _plugins: [Object],
       options: undefined,
       scope: undefined,
       state: undefined,
       _currentPluginApply: undefined },
    resource: 'e:\\git\\yspm\\src\\g\\js\\g.js',
    loaders: 
     [ 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js',
       'e:\\git\\yspm\\lib\\label-module-loader.js' ],
    fileDependencies: [ 'e:\\git\\yspm\\src\\g\\js\\g.js' ],
    contextDependencies: [],
    error: null,
    _source: 
     SourceMapSource {
       _value: '/* src/g/js/g.js */\n\nvar Event = require(\'common/js/core/event\');\n\nvar G = $.extend(new Event(), {\n\tinit: function (config) {\n\t\tvar self = this;\n\t\tconfig = config || {};\n\t}\n});\nmodule.exports = G;',
       _name: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\g\\js\\g.js',
       _sourceMap: [Object],
       _originalSource: undefined,
       _innerSourceMap: undefined },
    meta: {},
    assets: {},
    built: true,
    _cachedSource: null,
    issuer: 'multi common',
    optional: false,
    useSourceMap: true,
    building: undefined,
    buildTimestamp: 1458630613662,
    cacheable: false },
  DependenciesBlock {
    dependencies: [ [Object], [Object] ],
    blocks: [],
    variables: [],
    context: 'e:\\git\\yspm\\src\\common\\js\\core',
    reasons: [ [Object], [Object] ],
    debugId: 1006,
    lastId: -1,
    id: 2,
    index: 2,
    index2: 1,
    chunks: [ [Object] ],
    warnings: [],
    dependenciesWarnings: [],
    errors: [],
    dependenciesErrors: [],
    request: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\common\\js\\core\\event.js',
    userRequest: 'e:\\git\\yspm\\src\\common\\js\\core\\event.js',
    rawRequest: 'common/js/core/event',
    parser: 
     Parser {
       _plugins: [Object],
       options: undefined,
       scope: undefined,
       state: undefined,
       _currentPluginApply: undefined },
    resource: 'e:\\git\\yspm\\src\\common\\js\\core\\event.js',
    loaders: 
     [ 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js',
       'e:\\git\\yspm\\lib\\label-module-loader.js' ],
    fileDependencies: [ 'e:\\git\\yspm\\src\\common\\js\\core\\event.js' ],
    contextDependencies: [],
    error: null,
    _source: 
     SourceMapSource {
       _value: '/* src/common/js/core/event.js */\n\nvar Class = require(\'common/js/core/class\');\n\nvar Event = Class({\n\tinitialize: function () {\n\t\t//this.__event = window.Zepto ? new window.Zepto.Event : $({});\n\t\tthis.__event = $({});\n\t}\n});\n\nvar proto = Event.prototype;\n\n[\'bind\', \'one\'].forEach(function (method) {\n\tproto[method] = function (type, handler, context) {\n\t\tif ($.isPlainObject(type)) {\n\t\t\tfor (var i in type) this[method](i, type[i]);\n\t\t} else {\n\t\t\tvar event = this.__event;\n\t\t\tvar callback = function () {\n\t\t\t\treturn handler.apply(context || event, arguments.length > 0 ? window.Zepto ? arguments : Array.prototype.slice.call(arguments, 1) : []);\n\t\t\t};\n\t\t\tevent[method].call(event, type, callback);\n\t\t\thandler.guid = callback.guid;\n\t\t}\n\t\treturn this;\n\t};\n});\n[\'unbind\', \'trigger\', \'triggerHandler\'].forEach(function (method) {\n\tproto[method] = function () {\n\t\tvar event = this.__event;\n\t\t//\t\tif (require.debug) {\n\t\t//\t\t\tconsole.log(\'[event] \' + this.constructor.__mid + \' : \' + arguments[0], arguments[1]);\n\t\t//\t\t}\n\t\tvar ret = event[method].apply(event, arguments);\n\t\t//\t\tif (require.debug && ret != event && ret != undefined) {\n\t\t//\t\t\tconsole.log(ret);\n\t\t//\t\t}\n\t\treturn ret;\n\t};\n});\n\nproto.fire = proto.trigger;\nproto.firing = proto.triggerHandler;\nEvent.mix = function (receiver) {\n\treturn $.extend(receiver, new Event());\n};\n\nmodule.exports = Event;',
       _name: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\common\\js\\core\\event.js',
       _sourceMap: [Object],
       _originalSource: undefined,
       _innerSourceMap: undefined },
    meta: {},
    assets: {},
    built: true,
    _cachedSource: null,
    issuer: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\g\\js\\g.js',
    optional: false,
    useSourceMap: true,
    building: undefined,
    buildTimestamp: 1458630613743,
    cacheable: false },
  DependenciesBlock {
    dependencies: [],
    blocks: [],
    variables: [],
    context: 'e:\\git\\yspm\\src\\common\\js\\core',
    reasons: [ [Object] ],
    debugId: 1010,
    lastId: -1,
    id: 3,
    index: 3,
    index2: 0,
    chunks: [ [Object] ],
    warnings: [],
    dependenciesWarnings: [],
    errors: [],
    dependenciesErrors: [],
    request: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\common\\js\\core\\class.js',
    userRequest: 'e:\\git\\yspm\\src\\common\\js\\core\\class.js',
    rawRequest: 'common/js/core/class',
    parser: 
     Parser {
       _plugins: [Object],
       options: undefined,
       scope: undefined,
       state: undefined,
       _currentPluginApply: undefined },
    resource: 'e:\\git\\yspm\\src\\common\\js\\core\\class.js',
    loaders: 
     [ 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js',
       'e:\\git\\yspm\\lib\\label-module-loader.js' ],
    fileDependencies: [ 'e:\\git\\yspm\\src\\common\\js\\core\\class.js' ],
    contextDependencies: [],
    error: null,
    _source: 
     SourceMapSource {
       _value: '/* src/common/js/core/class.js */\n\nfunction init() {\n\treturn function () {\n\t\tif (this.initialize) {\n\t\t\tthis.initialize.apply(this, arguments);\n\t\t}\n\t};\n}\n\nfunction extend(protoProps, staticProps) {\n\tvar parent = this;\n\n\tvar child = init();\n\n\t$.extend(child, parent, staticProps);\n\n\tvar proto = Object.create(parent.prototype);\n\tproto.constructor = child;\n\tchild.prototype = proto;\n\n\t$.extend(child.prototype, protoProps);\n\n\tchild.superClass = parent.prototype;\n\n\treturn child;\n}\n\nvar Class = function (protoProps) {\n\tvar cls = init();\n\n\t$.extend(cls.prototype, protoProps);\n\n\tcls.extend = extend;\n\n\treturn cls;\n};\n\nClass.extend = extend;\n\nmodule.exports = Class;',
       _name: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\common\\js\\core\\class.js',
       _sourceMap: [Object],
       _originalSource: undefined,
       _innerSourceMap: undefined },
    meta: {},
    assets: {},
    built: true,
    _cachedSource: null,
    issuer: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\common\\js\\core\\event.js',
    optional: false,
    useSourceMap: true,
    building: undefined,
    buildTimestamp: 1458630613859,
    cacheable: false },
  DependenciesBlock {
    dependencies: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    blocks: [],
    variables: [],
    context: 'e:\\git\\yspm\\src\\g\\js',
    reasons: [ [Object] ],
    debugId: 1003,
    lastId: -1,
    id: 4,
    index: 4,
    index2: 5,
    chunks: [ [Object] ],
    warnings: [],
    dependenciesWarnings: [],
    errors: [],
    dependenciesErrors: [],
    request: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\g\\js\\g2.js',
    userRequest: 'e:\\git\\yspm\\src\\g\\js\\g2.js',
    rawRequest: 'e:\\git\\yspm\\src\\g\\js\\g2.js',
    parser: 
     Parser {
       _plugins: [Object],
       options: undefined,
       scope: undefined,
       state: undefined,
       _currentPluginApply: undefined },
    resource: 'e:\\git\\yspm\\src\\g\\js\\g2.js',
    loaders: 
     [ 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js',
       'e:\\git\\yspm\\lib\\label-module-loader.js' ],
    fileDependencies: [ 'e:\\git\\yspm\\src\\g\\js\\g2.js' ],
    contextDependencies: [],
    error: null,
    _source: 
     SourceMapSource {
       _value: '/* src/g/js/g2.js */\n\nvar Event = require(\'common/js/core/event\');\nvar Cookie = require(\'common/js/core/cookie\');\nvar Url = require(\'common/js/util/url\');\n\nconsole.log(\'g2...\');',
       _name: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\g\\js\\g2.js',
       _sourceMap: [Object],
       _originalSource: undefined,
       _innerSourceMap: undefined },
    meta: {},
    assets: {},
    built: true,
    _cachedSource: null,
    issuer: 'multi common',
    optional: false,
    useSourceMap: true,
    building: undefined,
    buildTimestamp: 1458630613662,
    cacheable: false },
  DependenciesBlock {
    dependencies: [],
    blocks: [],
    variables: [],
    context: 'e:\\git\\yspm\\src\\common\\js\\core',
    reasons: [ [Object], [Object] ],
    debugId: 1004,
    lastId: -1,
    id: 5,
    index: 5,
    index2: 3,
    chunks: [ [Object] ],
    warnings: [],
    dependenciesWarnings: [],
    errors: [],
    dependenciesErrors: [],
    request: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\common\\js\\core\\cookie.js',
    userRequest: 'e:\\git\\yspm\\src\\common\\js\\core\\cookie.js',
    rawRequest: 'common/js/core/cookie',
    parser: 
     Parser {
       _plugins: [Object],
       options: undefined,
       scope: undefined,
       state: undefined,
       _currentPluginApply: undefined },
    resource: 'e:\\git\\yspm\\src\\common\\js\\core\\cookie.js',
    loaders: 
     [ 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js',
       'e:\\git\\yspm\\lib\\label-module-loader.js' ],
    fileDependencies: [ 'e:\\git\\yspm\\src\\common\\js\\core\\cookie.js' ],
    contextDependencies: [],
    error: null,
    _source: 
     SourceMapSource {
       _value: '/* src/common/js/core/cookie.js */\n\nmodule.exports = function (win, n, v, op) {\n\tif (typeof win == "string") {\n\t\top = v;\n\t\tv = n;\n\t\tn = win;\n\t\twin = window;\n\t}\n\tif (v !== undefined) {\n\t\top = op || {};\n\t\tvar date,\n\t\t    expires = "";\n\t\tif (op.expires) {\n\t\t\tif (op.expires.constructor == Date) {\n\t\t\t\tdate = op.expires;\n\t\t\t} else {\n\t\t\t\tdate = new Date();\n\t\t\t\tdate.setTime(date.getTime() + op.expires * 24 * 60 * 60 * 1000);\n\t\t\t}\n\t\t\texpires = \'; expires=\' + date.toGMTString();\n\t\t}\n\t\tvar path = op.path ? \'; path=\' + op.path : \'\';\n\t\tvar domain = op.domain ? \'; domain=\' + op.domain : \'\';\n\t\tvar secure = op.secure ? \'; secure\' : \'\';\n\t\twin.document.cookie = [n, \'=\', encodeURIComponent(v), expires, path, domain, secure].join(\'\');\n\t} else {\n\t\tv = win.document.cookie.match(new RegExp("(?:\\\\s|^)" + n + "\\\\=([^;]*)"));\n\t\treturn v ? decodeURIComponent(v[1]) : null;\n\t}\n};',
       _name: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\common\\js\\core\\cookie.js',
       _sourceMap: [Object],
       _originalSource: undefined,
       _innerSourceMap: undefined },
    meta: {},
    assets: {},
    built: true,
    _cachedSource: null,
    issuer: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\passport\\js\\login.js',
    optional: false,
    useSourceMap: true,
    building: undefined,
    buildTimestamp: 1458630613742,
    cacheable: false },
  DependenciesBlock {
    dependencies: [],
    blocks: [],
    variables: [],
    context: 'e:\\git\\yspm\\src\\common\\js\\util',
    reasons: [ [Object] ],
    debugId: 1009,
    lastId: -1,
    id: 6,
    index: 6,
    index2: 4,
    chunks: [ [Object] ],
    warnings: [],
    dependenciesWarnings: [],
    errors: [],
    dependenciesErrors: [],
    request: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\common\\js\\util\\url.js',
    userRequest: 'e:\\git\\yspm\\src\\common\\js\\util\\url.js',
    rawRequest: 'common/js/util/url',
    parser: 
     Parser {
       _plugins: [Object],
       options: undefined,
       scope: undefined,
       state: undefined,
       _currentPluginApply: undefined },
    resource: 'e:\\git\\yspm\\src\\common\\js\\util\\url.js',
    loaders: 
     [ 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js',
       'e:\\git\\yspm\\lib\\label-module-loader.js' ],
    fileDependencies: [ 'e:\\git\\yspm\\src\\common\\js\\util\\url.js' ],
    contextDependencies: [],
    error: null,
    _source: 
     SourceMapSource {
       _value: '/* src/common/js/util/url.js */\n\nvar isIe = /msie/.test(navigator.userAgent.toLowerCase());\n/**\n * @public 跳到到指定地址，相对于open或location=，但是可以避免IE里location跳转时获取不到referrer的问题\n * @reference http://webbugtrack.blogspot.com/2008/11/bug-421-ie-fails-to-pass-http-referer.html\n * @TODO 会引起点击统计无法获得正确的位置编码\n */\nfunction openURL(url, target) {\n\tif (!isIe) {\n\t\tif (target) window.open(url, target);else location.href = url;\n\t} else {\n\t\tvar a = $(\'<a href="\' + url + \'" target="\' + (target || \'_self\') + \'" data-openurl="true"> </a>\')[0];\n\t\tdocument.body.appendChild(a);\n\t\ta.click();\n\t}\n}\n\nfunction params(url) {\n\turl = url || location.search || location.href;\n\tvar params = {},\n\t    result = url.match(/[^\\s&?#=\\/]+=[^\\s&?#=]+/g);\n\tif (result) for (var i = 0, l = result.length; i < l; i++) {\n\t\tvar n = result[i].split(\'=\');\n\t\tparams[n[0]] = decodeURIComponent(n[1]);\n\t}\n\treturn params;\n}\n\nfunction parseURL(url) {\n\tif (!/http(s)?:\\/\\/.+/.test(url)) {\n\t\turl = \'http://\' + url;\n\t}\n\tvar a = document.createElement(\'a\');\n\ta.href = url;\n\treturn {\n\t\tsource: url,\n\t\tprotocol: a.protocol.replace(\':\', \'\'),\n\t\thost: a.hostname,\n\t\tport: a.port || \'80\',\n\t\tquery: a.search,\n\t\tparams: params(url),\n\t\tfile: (a.pathname.match(/\\/([^\\/?#]+)$/i) || [, \'\'])[1],\n\t\thash: a.hash.replace(\'#\', \'\'),\n\t\tpath: a.pathname.replace(/^([^\\/])/, \'/$1\'),\n\t\trelative: (a.href.match(/tps?:\\/\\/[^\\/]+(.+)/) || [, \'\'])[1],\n\t\tsegments: a.pathname.replace(/^\\//, \'\').split(\'/\')\n\t};\n}\n\nmodule.exports = {\n\topenURL: openURL,\n\tparams: params,\n\tparseURL: parseURL\n};',
       _name: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\common\\js\\util\\url.js',
       _sourceMap: [Object],
       _originalSource: undefined,
       _innerSourceMap: undefined },
    meta: {},
    assets: {},
    built: true,
    _cachedSource: null,
    issuer: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\g\\js\\g2.js',
    optional: false,
    useSourceMap: true,
    building: undefined,
    buildTimestamp: 1458630613744,
    cacheable: false },
  DependenciesBlock {
    dependencies: [ [Object], [Object], [Object], [Object] ],
    blocks: [],
    variables: [],
    context: 'e:\\git\\yspm\\src\\passport\\js',
    reasons: [],
    debugId: 1001,
    lastId: -1,
    id: 0,
    index: 7,
    index2: 8,
    chunks: [ [Object] ],
    warnings: [],
    dependenciesWarnings: [],
    errors: [],
    dependenciesErrors: [],
    request: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\passport\\js\\login.js',
    userRequest: 'e:\\git\\yspm\\src\\passport\\js\\login.js',
    rawRequest: 'e:\\git\\yspm\\src\\passport\\js\\login.js',
    parser: 
     Parser {
       _plugins: [Object],
       options: undefined,
       scope: undefined,
       state: undefined,
       _currentPluginApply: undefined },
    resource: 'e:\\git\\yspm\\src\\passport\\js\\login.js',
    loaders: 
     [ 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js',
       'e:\\git\\yspm\\lib\\label-module-loader.js' ],
    fileDependencies: [ 'e:\\git\\yspm\\src\\passport\\js\\login.js' ],
    contextDependencies: [],
    error: null,
    _source: 
     SourceMapSource {
       _value: '/* src/passport/js/login.js */\n\nvar Cookie = require(\'common/js/core/cookie\');\nvar Serialize = require(\'common/js/util/serialize\');\n\nconsole.log(\'login.js\');\nSerialize.test();',
       _name: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\passport\\js\\login.js',
       _sourceMap: [Object],
       _originalSource: undefined,
       _innerSourceMap: undefined },
    meta: {},
    assets: {},
    built: true,
    _cachedSource: null,
    issuer: null,
    useSourceMap: true,
    building: undefined,
    buildTimestamp: 1458630613648,
    cacheable: false },
  DependenciesBlock {
    dependencies: [],
    blocks: [],
    variables: [],
    context: 'e:\\git\\yspm\\src\\common\\js\\util',
    reasons: [ [Object] ],
    debugId: 1008,
    lastId: -1,
    id: 7,
    index: 8,
    index2: 7,
    chunks: [ [Object] ],
    warnings: [],
    dependenciesWarnings: [],
    errors: [],
    dependenciesErrors: [],
    request: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\common\\js\\util\\serialize.js',
    userRequest: 'e:\\git\\yspm\\src\\common\\js\\util\\serialize.js',
    rawRequest: 'common/js/util/serialize',
    parser: 
     Parser {
       _plugins: [Object],
       options: undefined,
       scope: undefined,
       state: undefined,
       _currentPluginApply: undefined },
    resource: 'e:\\git\\yspm\\src\\common\\js\\util\\serialize.js',
    loaders: 
     [ 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js',
       'e:\\git\\yspm\\lib\\label-module-loader.js' ],
    fileDependencies: [ 'e:\\git\\yspm\\src\\common\\js\\util\\serialize.js' ],
    contextDependencies: [],
    error: null,
    _source: 
     SourceMapSource {
       _value: '/* src/common/js/util/serialize.js */\n\nmodule.exports = {\n\tarrayToJson: function (array) {\n\t\tif ($.type(array) !== \'array\') return;\n\t\tvar o = {};\n\t\tarray.forEach(function (item, i) {\n\t\t\tif (!(item.name in o)) {\n\t\t\t\to[item.name] = item.value;\n\t\t\t} else {\n\t\t\t\tif ($.type(o[item.name]) != \'array\') {\n\t\t\t\t\to[item.name] = [o[item.name]];\n\t\t\t\t}\n\t\t\t\to[item.name].push(item.value);\n\t\t\t}\n\t\t});\n\t\treturn o;\n\t},\n\ttest: function () {\n\t\tconsole.log(\'serialize module ...\');\n\t}\n};',
       _name: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\common\\js\\util\\serialize.js',
       _sourceMap: [Object],
       _originalSource: undefined,
       _innerSourceMap: undefined },
    meta: {},
    assets: {},
    built: true,
    _cachedSource: null,
    issuer: 'e:\\git\\yspm\\node_modules\\babel-loader\\index.js!e:\\git\\yspm\\lib\\label-module-loader.js!e:\\git\\yspm\\src\\passport\\js\\login.js',
    optional: false,
    useSourceMap: true,
    building: undefined,
    buildTimestamp: 1458630613744,
    cacheable: false } ]
